<#

Author       : Lakshmanan Thangaraj
Version      : 1.1
Created-On   : 29 July 2026
Modified-On  : 29 July 2026

.SYNOPSIS
    Offline Azure NSG Security & Compliance Gap Analysis Tool.
    Requirement 1 - Existing NSG Standardization and Compliance Assessment.
    Step 2: Analyze the baseline NSG inventory produced by Get-AzureNSGInventory
    for security risks, hygiene issues, and compliance gaps.

.DESCRIPTION
    Consumes the CSV produced by Get-AzureNSGInventory.ps1 (v1.2 or later) and
    runs a set of rule-level and NSG-level checks entirely offline, so re-running
    an analysis does not require re-querying Azure or holding an Azure session:
        - Any-Any (fully open) Allow rules, inbound and outbound
        - RDP (3389) and SSH (22) exposed directly to the Internet
        - Other sensitive management/service ports exposed to the Internet
          (WinRM, SMB, RPC, SQL/MySQL/PostgreSQL, Redis, MongoDB, VNC, etc.)
        - Wide destination port ranges exposed to the Internet
        - Priority conflicts (a rule shadowed/made unreachable by an earlier,
          conflicting-action rule with an overlapping scope)
        - Duplicate rules (different names, identical effective scope)
        - Rules missing a description
        - Orphaned NSGs (no subnet or NIC association)
        - Unused NSGs (no custom rules - relying entirely on Azure defaults)
        - NSG rule sprawl (custom rule count above a configurable threshold)

    Optionally (-IncludeFlowLogCheck), the function connects to Azure to check
    whether each NSG (or its associated virtual network) has flow logging
    enabled, covering both legacy NSG Flow Logs and the newer VNet Flow Logs.

    Findings are risk-rated (Critical/High/Medium/Low/Informational), mapped to
    a general compliance reference, and exported as a detailed CSV plus a
    per-NSG summary CSV. An optional JSON export supports downstream tooling
    or SIEM ingestion.

.PARAMETER CsvPath
    Mandatory. Path to the NSG inventory CSV generated by Get-AzureNSGInventory.ps1
    (v1.2 or later). Must exist and have a .csv extension.

.PARAMETER OutputPath
    Optional. Directory path where the findings/summary reports will be saved.
    Defaults to the current directory. Created automatically if it does not exist.

.PARAMETER ReportPrefix
    Optional. Prefix for the output report filenames. Default: "NSG_Compliance".
    Must not contain path separators or path-traversal sequences, since it is
    used to build output file names.

.PARAMETER WidePortRangeThreshold
    Optional. A destination port range wider than this many ports, exposed to
    the Internet, is flagged as a "wide port range" finding. Default: 100.

.PARAMETER RuleSprawlThreshold
    Optional. NSGs with more custom rules than this value are flagged as an
    informational "rule sprawl" finding. Default: 50.

.PARAMETER IncludeFlowLogCheck
    Optional switch. When specified, connects to Azure and checks Network
    Watcher flow log configuration (legacy NSG Flow Logs and VNet Flow Logs)
    for every NSG present in the CSV. Requires Az.Accounts and Az.Network and
    Reader access to Network Watcher resources in the target subscriptions.

.PARAMETER IncludeJsonExport
    Optional switch. When specified, also exports a JSON summary (finding
    counts by severity and category, plus per-NSG compliance scores)
    alongside the CSV reports.

.PARAMETER FailOnCritical
    Optional switch. When specified, throws a terminating error if any
    Critical-severity finding exists, after all reports have been exported.
    Intended for CI/CD pipeline gating - the caller decides how to act on it.

.INPUTS
    None. This function does not accept pipeline input.

.OUTPUTS
    None directly to the pipeline.

    Writes two CSV reports to disk (detailed findings + per-NSG summary), and
    optionally a JSON summary, that can be:
        - Opened directly in Excel for review and remediation tracking
        - Imported into Power BI
        - Used as the input dataset for a future
          Generate-AzureNSGComplianceDashboard.ps1

.EXAMPLE
    # Analyze a previously collected inventory CSV
    Test-AzureNSGCompliance -CsvPath "C:\Reports\NSG_Inventory_20260729_101500.csv"

.EXAMPLE
    # Analyze and also check flow log coverage against live Azure data
    Test-AzureNSGCompliance -CsvPath "C:\Reports\NSG_Inventory_20260729_101500.csv" -IncludeFlowLogCheck

.EXAMPLE
    # Custom thresholds, JSON export, and CI/CD gating on Critical findings
    Test-AzureNSGCompliance -CsvPath ".\NSG_Inventory_20260729_101500.csv" `
        -OutputPath "C:\Reports\Compliance" -ReportPrefix "Prod_NSG_Gaps" `
        -WidePortRangeThreshold 50 -RuleSprawlThreshold 30 `
        -IncludeJsonExport -FailOnCritical

.EXAMPLE
    # Full Requirement 1 pipeline

    Get-AzureNSGInventory -OutputPath "C:\Reports"

    Test-AzureNSGCompliance -CsvPath "C:\Reports\NSG_Inventory_<timestamp>.csv" `
        -OutputPath "C:\Reports" -IncludeFlowLogCheck -IncludeJsonExport

    Collects the Azure NSG inventory, then runs the offline + flow-log-aware
    compliance analysis against it, ready for Step 3 (dashboard visualization).

.NOTES
    ─────────────────────────────────────────────────────────────────────────
    Version History:
    ─────────────────────────────────────────────────────────────────────────
    1.1 (29-Jul-2026) - Fixed a single-element array unwrapping bug in
                        ConvertTo-PortRanges: when a port spec produced
                        exactly one range (e.g. a single port or "*"),
                        PowerShell's pipeline flattened the returned
                        array-of-arrays down to a plain 2-int array,
                        causing "Unable to index into an object of type
                        System.Int32" and silently aborting analysis for
                        the affected NSG. Fixed by prefixing both return
                        statements with the unary comma operator so the
                        array-of-arrays shape survives the return. No
                        change to check logic, thresholds, or CSV/JSON
                        schema.
    1.0 (29-Jul-2026) - Initial release.

    ─────────────────────────────────────────────────────────────────────────
    Pre-Requisites:
    ─────────────────────────────────────────────────────────────────────────
    1. A CSV produced by Get-AzureNSGInventory.ps1 v1.2 or later (earlier
       versions do not emit the merged SourceAddressAll/SourcePortAll/
       DestinationAddressAll/DestinationPortAll columns this function relies
       on for the exposure checks).
    2. PowerShell 5.1 or later.
    3. Only if -IncludeFlowLogCheck is used: Az.Accounts and Az.Network
       modules, plus Reader access on the target subscriptions' Network
       Watcher resources. Not required for the default offline analysis.

    ─────────────────────────────────────────────────────────────────────────
    Execution Flow:
    ─────────────────────────────────────────────────────────────────────────
    1. Validate -CsvPath exists and, once imported, contains the columns this
       function depends on; error out with guidance if the schema looks like
       an older inventory version.
    2. If -IncludeFlowLogCheck: verify Az.Accounts/Az.Network are installed,
       verify/establish an authenticated session (same reuse-or-reauth prompt
       pattern as Get-AzureNSGInventory), then for every distinct subscription
       in the CSV, enumerate Network Watchers and their configured flow logs
       (both NSG-scoped and VNet-scoped) into an in-memory lookup table.
    3. Group the CSV rows by NSG. For each NSG: evaluate NSG-level findings
       (orphaned, unused, rule sprawl, missing flow logs), then evaluate
       Inbound and Outbound rule sets separately for rule-level findings
       (Any-Any, RDP/SSH/sensitive-port/wide-port Internet exposure, missing
       description, duplicate rules, and priority-conflict/shadowing).
       One subscription/NSG failing to parse does not abort the run.
    4. Risk-rate every finding and attach a general compliance reference.
    5. Export the detailed findings CSV and a per-NSG summary CSV (with a
       simple 0-100 compliance score) to -OutputPath. Optionally export a
       JSON summary. Optionally throw if -FailOnCritical and Critical
       findings exist, for CI/CD gating.

    ─────────────────────────────────────────────────────────────────────────
    Known Limitations:
    ─────────────────────────────────────────────────────────────────────────
    - Address/protocol scope comparisons (used for the Any-Any check and for
      priority-conflict/shadowing detection) are exact-string-or-wildcard
      only; this function does NOT perform CIDR subnet math. Two distinct,
      non-wildcard IP ranges that partially overlap (e.g. 10.0.0.0/16 vs.
      10.0.1.0/24) will not be detected as overlapping. Only exact matches or
      "*"/"Any"/"Internet" wildcards are treated as overlapping scopes.
    - Priority-conflict detection only considers Custom rules (Default rules
      are Azure-managed, always present, and not user-actionable).
    - The VNet Flow Log correlation (-IncludeFlowLogCheck) matches by virtual
      network NAME, parsed from the inventory's AssociatedSubnets column,
      because that column does not carry full VNet resource IDs. If two
      different VNets in the same subscription share the same name across
      resource groups, this heuristic can produce a false "flow logs found"
      match. Consider extending Get-AzureNSGInventory to also capture subnet/
      VNet resource IDs for a fully unambiguous correlation.
    - Port-range parsing supports single ports, comma-separated lists, and
      "start-end" ranges. Any other/unexpected port token format is skipped
      silently rather than guessed at.
    - ComplianceReference values point to the general CIS Azure Foundations
      Benchmark network-security domain and the Azure Security Benchmark "NS"
      control family. Exact control/section numbers vary by benchmark
      version, so map these to the specific version your organization has
      adopted rather than treating the text as an authoritative citation.
    - Wide-port-range, sensitive-port, and Any-Any findings can all fire for
      the same underlying rule; this is intentional (a single rule can
      violate more than one check) and is not de-duplicated.

.LINK
    Get-AzureNSGInventory.ps1 - Azure NSG Inventory and Data Collection Tool
    https://github.com/lakshmananthangaraj/Cloud-Identity-Toolkit/blob/main/Azure/Network/Get-AzureNSGInventory.ps1

.LINK
    https://learn.microsoft.com/en-us/azure/network-watcher/vnet-flow-logs-overview

.LINK
    https://learn.microsoft.com/en-us/security/benchmark/azure/security-controls-v3-network-security

#>


Function Test-AzureNSGCompliance
{
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, HelpMessage = "Path to the NSG inventory CSV produced by Get-AzureNSGInventory.")]
        [ValidateScript({
            if (-not (Test-Path -Path $_ -PathType Leaf))
            {
                throw "CsvPath '$_' was not found."
            }
            if ([System.IO.Path]::GetExtension($_) -ne ".csv")
            {
                throw "CsvPath must point to a .csv file."
            }
            $true
        })]
        [string]$CsvPath,

        [Parameter(Mandatory = $false, HelpMessage = "Directory path to save the compliance reports.")]
        [ValidateNotNullOrEmpty()]
        [string]$OutputPath = (Get-Location).Path,

        [Parameter(Mandatory = $false, HelpMessage = "Prefix for the output report filenames.")]
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            if ($_ -match '\.\.' -or $_ -match '[\\/:\*\?"<>\|]')
            {
                throw "ReportPrefix must not contain path separators, path-traversal sequences ('..'), or invalid filename characters."
            }
            $true
        })]
        [string]$ReportPrefix = "NSG_Compliance",

        [Parameter(Mandatory = $false, HelpMessage = "Destination port range width (in ports) above which an Internet-exposed rule is flagged as wide.")]
        [ValidateRange(1, 65535)]
        [int]$WidePortRangeThreshold = 100,

        [Parameter(Mandatory = $false, HelpMessage = "Custom rule count above which an NSG is flagged for rule sprawl.")]
        [ValidateRange(1, 1000)]
        [int]$RuleSprawlThreshold = 50,

        [Parameter(Mandatory = $false, HelpMessage = "Check live Azure flow log configuration (NSG + VNet) for each NSG in the CSV.")]
        [switch]$IncludeFlowLogCheck,

        [Parameter(Mandatory = $false, HelpMessage = "Also export a JSON summary alongside the CSV reports.")]
        [switch]$IncludeJsonExport,

        [Parameter(Mandatory = $false, HelpMessage = "Throw a terminating error after export if any Critical finding exists.")]
        [switch]$FailOnCritical
    )

    #region ── Helper: Wildcard / Internet-Source Evaluation ─────────────────────
    $script:BaseWildcardTokens = @('*', 'any', '0.0.0.0/0', '0.0.0.0', '::/0', '::0/0')

    Function Test-IsFullyWildcard
    {
        param(
            [string]$Value,
            [switch]$IncludeInternetTag
        )
        if ([string]::IsNullOrWhiteSpace($Value)) { return $false }
        $normalized = $Value.Trim().ToLowerInvariant()
        if ($normalized.Contains(",")) { return $false }
        $tokens = $script:BaseWildcardTokens
        if ($IncludeInternetTag) { $tokens = $tokens + @('internet') }
        return ($tokens -contains $normalized)
    }

    Function Test-ContainsInternetSource
    {
        param([string]$AddressAll)
        if ([string]::IsNullOrWhiteSpace($AddressAll)) { return $false }
        $tokens = $AddressAll -split ','
        foreach ($token in $tokens)
        {
            $normalized = $token.Trim().ToLowerInvariant()
            if (($script:BaseWildcardTokens -contains $normalized) -or ($normalized -eq 'internet'))
            {
                return $true
            }
        }
        return $false
    }

    Function Test-ScopeOverlap
    {
        # Conservative exact-match-or-wildcard overlap test for a single
        # merged scope value (protocol, source, or destination). See
        # Known Limitations: this is NOT CIDR-aware.
        param([string]$ValueA, [string]$ValueB)
        $a = if ($ValueA) { $ValueA.Trim().ToLowerInvariant() } else { "" }
        $b = if ($ValueB) { $ValueB.Trim().ToLowerInvariant() } else { "" }
        if ($a -eq '*' -or $a -eq 'any' -or $b -eq '*' -or $b -eq 'any') { return $true }
        return ($a -eq $b)
    }
    #endregion

    #region ── Helper: Port Spec Parsing ─────────────────────────────────────────
    Function ConvertTo-PortRanges
    {
        param([string]$Spec)
        $ranges = @()
        if ([string]::IsNullOrWhiteSpace($Spec) -or $Spec.Trim() -eq '*')
        {
            $ranges += , @(0, 65535)
            return , $ranges
        }
        $tokens = $Spec -split ','
        foreach ($token in $tokens)
        {
            $t = $token.Trim()
            if ($t -eq '') { continue }
            if ($t -eq '*')
            {
                $ranges += , @(0, 65535)
                continue
            }
            if ($t -match '^(\d+)-(\d+)$')
            {
                $ranges += , @([int]$matches[1], [int]$matches[2])
                continue
            }
            if ($t -match '^\d+$')
            {
                $ranges += , @([int]$t, [int]$t)
                continue
            }
            # Unrecognized token format - skipped silently, cannot be evaluated.
        }
        return , $ranges
    }

    Function Test-PortSpecContainsPort
    {
        param([string]$Spec, [int]$TargetPort)
        $ranges = ConvertTo-PortRanges -Spec $Spec
        foreach ($r in $ranges)
        {
            if ($TargetPort -ge $r[0] -and $TargetPort -le $r[1]) { return $true }
        }
        return $false
    }

    Function Test-PortRangeOverlap
    {
        param([string]$SpecA, [string]$SpecB)
        $rangesA = ConvertTo-PortRanges -Spec $SpecA
        $rangesB = ConvertTo-PortRanges -Spec $SpecB
        foreach ($a in $rangesA)
        {
            foreach ($b in $rangesB)
            {
                if ($a[0] -le $b[1] -and $b[0] -le $a[1]) { return $true }
            }
        }
        return $false
    }

    Function Get-PortSpecWidth
    {
        param([string]$Spec)
        $ranges = ConvertTo-PortRanges -Spec $Spec
        $width = 0
        foreach ($r in $ranges) { $width += ($r[1] - $r[0] + 1) }
        return $width
    }
    #endregion

    #region ── Helper: Finding Factory ───────────────────────────────────────────
    $script:CollectedAtUTC = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

    Function New-Finding
    {
        param(
            [PSCustomObject]$MetaRow,
            [string]$RuleName = "N/A",
            [string]$RuleDirection = "N/A",
            [string]$RulePriority = "N/A",
            [string]$CheckCategory,
            [string]$Severity,
            [string]$FindingText,
            [string]$Recommendation,
            [string]$ComplianceReference,
            [string]$RelatedRule = ""
        )
        return [PSCustomObject]@{
            ManagementGroup      = $MetaRow.ManagementGroup
            SubscriptionName     = $MetaRow.SubscriptionName
            SubscriptionId       = $MetaRow.SubscriptionId
            ResourceGroup        = $MetaRow.ResourceGroup
            NSGName              = $MetaRow.NSGName
            NSGResourceId        = $MetaRow.NSGResourceId
            NSGLocation          = $MetaRow.NSGLocation
            RuleName             = $RuleName
            RuleDirection        = $RuleDirection
            RulePriority         = $RulePriority
            CheckCategory        = $CheckCategory
            Severity             = $Severity
            Finding              = $FindingText
            Recommendation       = $Recommendation
            ComplianceReference  = $ComplianceReference
            RelatedRule          = $RelatedRule
            CollectedAtUTC       = $script:CollectedAtUTC
        }
    }
    #endregion

    #region ── Sensitive Ports Reference Table ───────────────────────────────────
    # RDP (3389) and SSH (22) are checked separately with their own dedicated,
    # higher-severity finding categories. This table covers other commonly
    # abused management/data ports.
    $sensitivePorts = [ordered]@{
        "23"    = "Telnet"
        "21"    = "FTP"
        "445"   = "SMB"
        "135"   = "RPC/DCOM"
        "1433"  = "MSSQL"
        "3306"  = "MySQL"
        "5432"  = "PostgreSQL"
        "5985"  = "WinRM-HTTP"
        "5986"  = "WinRM-HTTPS"
        "5900"  = "VNC"
        "6379"  = "Redis"
        "27017" = "MongoDB"
        "9200"  = "Elasticsearch"
        "11211" = "Memcached"
        "2049"  = "NFS"
    }
    $cisNetworkRef = "CIS Azure Foundations Benchmark - Network Security domain / Azure Security Benchmark - NS control family"
    #endregion

    #region ── Banner ────────────────────────────────────────────────────────────
    Write-Host ""
    Write-Host "╔══════════════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║          Azure NSG Security & Compliance Gap Analysis Tool           ║" -ForegroundColor Cyan
    Write-Host "║          Requirement 1 - NSG Standardization & Compliance            ║" -ForegroundColor Cyan
    Write-Host "╚══════════════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host ""
    #endregion

    #region ── Load & Validate Inventory CSV ─────────────────────────────────────
    Write-Host "[LOAD] Importing NSG inventory: $CsvPath" -ForegroundColor Yellow
    try
    {
        $csvData = @(Import-Csv -Path $CsvPath -ErrorAction Stop)
    }
    catch
    {
        Write-Error "[LOAD] Failed to import CSV '$CsvPath': $_"
        return
    }

    if ($csvData.Count -eq 0)
    {
        Write-Error "[LOAD] CSV '$CsvPath' contained no rows. Nothing to analyze."
        return
    }

    $requiredColumns = @(
        "ManagementGroup", "SubscriptionName", "SubscriptionId", "ResourceGroup",
        "NSGName", "NSGResourceId", "NSGLocation", "AssociatedSubnets", "AssociatedNICs",
        "TotalSubnetAssociations", "TotalNICAssociations", "RuleSource", "RuleName",
        "RuleDirection", "RulePriority", "RuleAccess", "RuleProtocol",
        "SourceAddressAll", "SourcePortAll", "DestinationAddressAll", "DestinationPortAll",
        "RuleDescription"
    )
    $csvColumns = ($csvData[0].PSObject.Properties | Select-Object -ExpandProperty Name)
    $missingColumns = @($requiredColumns | Where-Object { $csvColumns -notcontains $_ })

    if ($missingColumns.Count -gt 0)
    {
        Write-Error "[LOAD] CSV is missing required column(s): $($missingColumns -join ', '). This function requires a CSV produced by Get-AzureNSGInventory.ps1 v1.2 or later (merged SourceAddressAll/SourcePortAll/DestinationAddressAll/DestinationPortAll columns). Please regenerate the inventory and try again."
        return
    }

    Write-Host "[LOAD] Loaded $($csvData.Count) row(s) covering $((@($csvData | Select-Object -ExpandProperty NSGResourceId -Unique)).Count) NSG(s)." -ForegroundColor Green
    Write-Host ""
    #endregion

    #region ── Optional: Live Flow Log Lookup ────────────────────────────────────
    $nsgFlowLogTargets  = @{}   # key: lowercased NSG resource ID          -> $true if an enabled flow log targets it
    $vnetFlowLogNames   = @{}   # key: lowercased VNet name                -> $true if an enabled flow log targets a VNet with this name

    if ($IncludeFlowLogCheck)
    {
        Write-Host "[PRE-CHECK] -IncludeFlowLogCheck specified. Verifying required Az PowerShell modules..." -ForegroundColor Yellow
        $requiredModules = @("Az.Accounts", "Az.Network")
        $modulesOk = $true
        foreach ($mod in $requiredModules)
        {
            if (-not (Get-Module -ListAvailable -Name $mod))
            {
                Write-Warning "[PRE-CHECK] Required module '$mod' is not installed. Run: Install-Module -Name Az.Accounts, Az.Network -Scope CurrentUser -AllowClobber"
                $modulesOk = $false
            }
        }

        if (-not $modulesOk)
        {
            Write-Warning "[PRE-CHECK] Skipping flow log check due to missing module(s). Continuing with offline analysis only."
        }
        else
        {
            Write-Host "[PRE-CHECK] Required modules are available." -ForegroundColor Green
            Write-Host ""
            Write-Host "[AUTH] Checking for active Azure session..." -ForegroundColor Yellow

            $activeContext = $null
            try
            {
                $activeContext = Get-AzContext -ErrorAction SilentlyContinue
            }
            catch
            {
                $activeContext = $null
            }

            if ($null -eq $activeContext -or $null -eq $activeContext.Account)
            {
                Write-Host "[AUTH] No active Azure session detected. Initiating authentication..." -ForegroundColor Yellow
                try
                {
                    Connect-AzAccount -ErrorAction Stop -WarningAction SilentlyContinue | Out-Null
                    $activeContext = Get-AzContext
                    Write-Host "[AUTH] Authentication successful." -ForegroundColor Green
                }
                catch
                {
                    Write-Warning "[AUTH] Authentication failed: $_. Continuing with offline analysis only."
                    $IncludeFlowLogCheck = $false
                }
            }
            else
            {
                Write-Host "[AUTH] Active session found. Signed in as $($activeContext.Account.Id)" -ForegroundColor Green
                $reAuth = Read-Host "`n[AUTH] Use existing session? (Y/N, default=Y)"
                if ($reAuth -eq "N" -or $reAuth -eq "n")
                {
                    Write-Host "[AUTH] Disconnecting current session and re-authenticating..." -ForegroundColor Yellow
                    Disconnect-AzAccount -ErrorAction SilentlyContinue -WarningAction SilentlyContinue | Out-Null
                    try
                    {
                        Connect-AzAccount -ErrorAction Stop | Out-Null
                        $activeContext = Get-AzContext
                        Write-Host "[AUTH] Re-authentication successful." -ForegroundColor Green
                    }
                    catch
                    {
                        Write-Warning "[AUTH] Re-authentication failed: $_. Continuing with offline analysis only."
                        $IncludeFlowLogCheck = $false
                    }
                }
            }
            Write-Host ""
        }
    }

    if ($IncludeFlowLogCheck)
    {
        $distinctSubIds = @($csvData | Select-Object -ExpandProperty SubscriptionId -Unique)
        Write-Host "[FLOWLOGS] Enumerating Network Watcher flow log configuration across $($distinctSubIds.Count) subscription(s)..." -ForegroundColor Yellow

        foreach ($subId in $distinctSubIds)
        {
            try
            {
                Set-AzContext -SubscriptionId $subId -ErrorAction Stop -WarningAction SilentlyContinue | Out-Null
            }
            catch
            {
                Write-Warning "[FLOWLOGS] Could not switch context to subscription '$subId'. Skipping flow log check for this subscription."
                continue
            }

            $watchers = @()
            try
            {
                $watchers = @(Get-AzNetworkWatcher -ErrorAction Stop -WarningAction SilentlyContinue)
            }
            catch
            {
                Write-Warning "[FLOWLOGS] Could not retrieve Network Watchers for subscription '$subId': $_"
                continue
            }

            foreach ($watcher in $watchers)
            {
                $flowLogs = @()
                try
                {
                    $flowLogs = @(Get-AzNetworkWatcherFlowLog -NetworkWatcher $watcher -ErrorAction Stop -WarningAction SilentlyContinue)
                }
                catch
                {
                    Write-Verbose "[FLOWLOGS] No flow logs (or an access issue) for Network Watcher '$($watcher.Name)' in '$($watcher.Location)': $_"
                    continue
                }

                foreach ($flowLog in $flowLogs)
                {
                    if (-not $flowLog.Enabled) { continue }
                    $targetId = "$($flowLog.TargetResourceId)".ToLowerInvariant()
                    if ($targetId -match '/networksecuritygroups/')
                    {
                        $nsgFlowLogTargets[$targetId] = $true
                    }
                    elseif ($targetId -match '/virtualnetworks/([^/]+)$')
                    {
                        $vnetFlowLogNames[$matches[1].ToLowerInvariant()] = $true
                    }
                }
            }
        }
        Write-Host "[FLOWLOGS] Found $($nsgFlowLogTargets.Count) NSG-scoped and $($vnetFlowLogNames.Count) VNet-scoped enabled flow log(s)." -ForegroundColor Green
        Write-Host ""
    }
    #endregion

    #region ── Analysis ──────────────────────────────────────────────────────────
    $findings = [System.Collections.Generic.List[PSCustomObject]]::new()
    $nsgGroups = $csvData | Group-Object -Property NSGResourceId
    Write-Host "[ANALYZE] Evaluating $($nsgGroups.Count) NSG(s)..." -ForegroundColor Yellow

    foreach ($nsgGroup in $nsgGroups)
    {
        try
        {
            $nsgRows  = @($nsgGroup.Group)
            $metaRow  = $nsgRows[0]
            $customRows  = @($nsgRows | Where-Object { $_.RuleSource -eq 'Custom' })
            $customRuleCount = $customRows.Count

            #region ── NSG-Level Findings ────────────────────────────────────────
            $totalSubnetAssoc = 0
            $totalNicAssoc    = 0
            [void][int]::TryParse($metaRow.TotalSubnetAssociations, [ref]$totalSubnetAssoc)
            [void][int]::TryParse($metaRow.TotalNICAssociations, [ref]$totalNicAssoc)

            if ($totalSubnetAssoc -eq 0 -and $totalNicAssoc -eq 0)
            {
                $findings.Add((New-Finding -MetaRow $metaRow -CheckCategory "OrphanedNSG" -Severity "Low" `
                    -FindingText "NSG is not associated with any subnet or network interface." `
                    -Recommendation "Confirm the NSG is genuinely unused, then remove it to reduce clutter and management overhead. If retained intentionally (e.g. as a template), tag it accordingly." `
                    -ComplianceReference "Azure Security Benchmark - Asset Management (AM) control family"))
            }

            if ($nsgRows[0].RuleSource -eq 'N/A' -and $customRuleCount -eq 0)
            {
                $findings.Add((New-Finding -MetaRow $metaRow -CheckCategory "NoRulesDefined" -Severity "Informational" `
                    -FindingText "NSG reported no rules at all, not even Azure default rules. This is an unexpected state." `
                    -Recommendation "Verify this NSG manually in the Azure Portal; it may indicate a provisioning issue or an inventory collection timing artifact." `
                    -ComplianceReference "Internal hygiene"))
            }
            elseif ($customRuleCount -eq 0)
            {
                $findings.Add((New-Finding -MetaRow $metaRow -CheckCategory "UnusedNSG" -Severity "Informational" `
                    -FindingText "NSG has no custom security rules; it relies entirely on Azure default rules." `
                    -Recommendation "Confirm whether this NSG is actively protecting a workload. If so, add explicit custom rules reflecting intended traffic; if not, consider removing it." `
                    -ComplianceReference "Azure Security Benchmark - Asset Management (AM) control family"))
            }

            if ($customRuleCount -gt $RuleSprawlThreshold)
            {
                $findings.Add((New-Finding -MetaRow $metaRow -CheckCategory "RuleSprawl" -Severity "Informational" `
                    -FindingText "NSG has $customRuleCount custom rules, above the configured threshold of $RuleSprawlThreshold." `
                    -Recommendation "Review for consolidation opportunities; consider Application Security Groups (ASGs) to reduce rule count and improve maintainability." `
                    -ComplianceReference "Azure Security Benchmark - NS control family / operational maintainability"))
            }

            if ($IncludeFlowLogCheck -and ($totalSubnetAssoc -gt 0 -or $totalNicAssoc -gt 0))
            {
                $nsgIdLower = "$($metaRow.NSGResourceId)".ToLowerInvariant()
                $hasNsgFlowLog = $nsgFlowLogTargets.ContainsKey($nsgIdLower)

                $associatedVnetNames = @()
                if ($metaRow.AssociatedSubnets -and $metaRow.AssociatedSubnets -ne "None")
                {
                    $associatedVnetNames = @(
                        ($metaRow.AssociatedSubnets -split '\|') | ForEach-Object {
                            ($_ -split '/')[0].Trim().ToLowerInvariant()
                        } | Where-Object { $_ -and $_ -ne "unknown" } | Select-Object -Unique
                    )
                }
                $hasVnetFlowLog = $false
                foreach ($vnetName in $associatedVnetNames)
                {
                    if ($vnetFlowLogNames.ContainsKey($vnetName)) { $hasVnetFlowLog = $true; break }
                }

                if (-not $hasNsgFlowLog -and -not $hasVnetFlowLog)
                {
                    $findings.Add((New-Finding -MetaRow $metaRow -CheckCategory "MissingFlowLogs" -Severity "Medium" `
                        -FindingText "No enabled flow logging (NSG Flow Logs or VNet Flow Logs) was found covering this NSG or its associated virtual network(s)." `
                        -Recommendation "Enable VNet Flow Logs for the associated virtual network(s). NSG Flow Logs can no longer be newly created (creation closed 30-Jun-2025) and retire entirely on 30-Sep-2027, so VNet Flow Logs is the supported path going forward." `
                        -ComplianceReference "CIS Azure Foundations Benchmark - Network Security domain / Azure Security Benchmark - Logging & Threat Detection (LT) control family"))
                }
                elseif ($hasNsgFlowLog -and -not $hasVnetFlowLog)
                {
                    $findings.Add((New-Finding -MetaRow $metaRow -CheckCategory "LegacyFlowLogsInUse" -Severity "Informational" `
                        -FindingText "NSG is covered only by a legacy NSG Flow Log." `
                        -Recommendation "Plan migration to VNet Flow Logs ahead of the 30-Sep-2027 retirement of NSG Flow Logs." `
                        -ComplianceReference "Microsoft Azure Network Watcher retirement notice"))
                }
            }
            #endregion

            #region ── Rule-Level Findings (per direction) ───────────────────────
            foreach ($direction in @('Inbound', 'Outbound'))
            {
                $directionRows = @($nsgRows | Where-Object { $_.RuleDirection -eq $direction -and $_.RuleSource -ne 'N/A' })
                if ($directionRows.Count -eq 0) { continue }

                foreach ($row in $directionRows)
                {
                    $isAllow = ($row.RuleAccess -eq 'Allow')

                    #── Any-Any (fully open) ──────────────────────────────────
                    if ($isAllow -and
                        (Test-IsFullyWildcard -Value $row.RuleProtocol) -and
                        (Test-IsFullyWildcard -Value $row.SourceAddressAll -IncludeInternetTag) -and
                        (Test-IsFullyWildcard -Value $row.DestinationAddressAll) -and
                        (Test-IsFullyWildcard -Value $row.SourcePortAll) -and
                        (Test-IsFullyWildcard -Value $row.DestinationPortAll))
                    {
                        $severity = if ($direction -eq 'Inbound') { "Critical" } else { "Medium" }
                        $findings.Add((New-Finding -MetaRow $metaRow -RuleName $row.RuleName -RuleDirection $direction -RulePriority $row.RulePriority `
                            -CheckCategory "AnyToAnyAllow" -Severity $severity `
                            -FindingText "Rule '$($row.RuleName)' allows ANY protocol from ANY source to ANY destination on ANY port ($direction)." `
                            -Recommendation "Restrict source/destination address prefixes, protocol, and port ranges to the minimum required for the intended traffic." `
                            -ComplianceReference $cisNetworkRef))
                    }

                    if ($direction -eq 'Inbound' -and $isAllow -and $row.RuleProtocol -match '^(?i:\*|tcp)$')
                    {
                        $sourceIsInternet = Test-ContainsInternetSource -AddressAll $row.SourceAddressAll

                        #── RDP exposed to Internet ───────────────────────────
                        if ($sourceIsInternet -and (Test-PortSpecContainsPort -Spec $row.DestinationPortAll -TargetPort 3389))
                        {
                            $findings.Add((New-Finding -MetaRow $metaRow -RuleName $row.RuleName -RuleDirection $direction -RulePriority $row.RulePriority `
                                -CheckCategory "RDPExposedToInternet" -Severity "Critical" `
                                -FindingText "Rule '$($row.RuleName)' allows RDP (3389) inbound from the Internet." `
                                -Recommendation "Remove direct Internet access to RDP. Use Azure Bastion, a jump host, or a VPN/ExpressRoute connection, and restrict source to known management ranges." `
                                -ComplianceReference $cisNetworkRef))
                        }

                        #── SSH exposed to Internet ────────────────────────────
                        if ($sourceIsInternet -and (Test-PortSpecContainsPort -Spec $row.DestinationPortAll -TargetPort 22))
                        {
                            $findings.Add((New-Finding -MetaRow $metaRow -RuleName $row.RuleName -RuleDirection $direction -RulePriority $row.RulePriority `
                                -CheckCategory "SSHExposedToInternet" -Severity "Critical" `
                                -FindingText "Rule '$($row.RuleName)' allows SSH (22) inbound from the Internet." `
                                -Recommendation "Remove direct Internet access to SSH. Use Azure Bastion, a jump host, or a VPN/ExpressRoute connection, and restrict source to known management ranges." `
                                -ComplianceReference $cisNetworkRef))
                        }

                        #── Other sensitive ports exposed to Internet ─────────
                        if ($sourceIsInternet)
                        {
                            foreach ($portKey in $sensitivePorts.Keys)
                            {
                                if (Test-PortSpecContainsPort -Spec $row.DestinationPortAll -TargetPort ([int]$portKey))
                                {
                                    $svcName = $sensitivePorts[$portKey]
                                    $findings.Add((New-Finding -MetaRow $metaRow -RuleName $row.RuleName -RuleDirection $direction -RulePriority $row.RulePriority `
                                        -CheckCategory "SensitivePortExposedToInternet" -Severity "High" `
                                        -FindingText "Rule '$($row.RuleName)' allows $svcName (port $portKey) inbound from the Internet." `
                                        -Recommendation "Restrict source to trusted ranges, or route through a bastion/VPN. Avoid exposing management and data-store ports directly to the Internet." `
                                        -ComplianceReference $cisNetworkRef))
                                }
                            }
                        }

                        #── Wide destination port range exposed to Internet ──
                        if ($sourceIsInternet -and (Get-PortSpecWidth -Spec $row.DestinationPortAll) -gt $WidePortRangeThreshold)
                        {
                            $findings.Add((New-Finding -MetaRow $metaRow -RuleName $row.RuleName -RuleDirection $direction -RulePriority $row.RulePriority `
                                -CheckCategory "WidePortRangeExposedToInternet" -Severity "High" `
                                -FindingText "Rule '$($row.RuleName)' exposes a destination port range wider than $WidePortRangeThreshold ports ('$($row.DestinationPortAll)') to the Internet." `
                                -Recommendation "Narrow the port range to only the specific ports required." `
                                -ComplianceReference $cisNetworkRef))
                        }
                    }

                    #── Missing description (Custom rules only) ───────────────
                    if ($row.RuleSource -eq 'Custom' -and [string]::IsNullOrWhiteSpace($row.RuleDescription))
                    {
                        $findings.Add((New-Finding -MetaRow $metaRow -RuleName $row.RuleName -RuleDirection $direction -RulePriority $row.RulePriority `
                            -CheckCategory "MissingDescription" -Severity "Informational" `
                            -FindingText "Custom rule '$($row.RuleName)' has no description." `
                            -Recommendation "Add a description capturing intent/owner/change-ticket to support future audits and change management." `
                            -ComplianceReference "Azure Security Benchmark - Governance & Strategy (GS) control family"))
                    }
                }

                #── Duplicate rules (Custom only, same effective scope) ───────
                $directionCustomRows = @($directionRows | Where-Object { $_.RuleSource -eq 'Custom' })
                $dupGroups = $directionCustomRows | Group-Object -Property {
                    "$($_.RuleAccess)|$($_.RuleProtocol)|$($_.SourceAddressAll)|$($_.SourcePortAll)|$($_.DestinationAddressAll)|$($_.DestinationPortAll)".Trim().ToLowerInvariant()
                }
                foreach ($dupGroup in $dupGroups)
                {
                    if ($dupGroup.Count -gt 1)
                    {
                        $namesInGroup = @($dupGroup.Group | Select-Object -ExpandProperty RuleName)
                        foreach ($dupRow in $dupGroup.Group)
                        {
                            $siblings = ($namesInGroup | Where-Object { $_ -ne $dupRow.RuleName }) -join ', '
                            $findings.Add((New-Finding -MetaRow $metaRow -RuleName $dupRow.RuleName -RuleDirection $direction -RulePriority $dupRow.RulePriority `
                                -CheckCategory "DuplicateRule" -Severity "Low" `
                                -FindingText "Rule '$($dupRow.RuleName)' has the same effective scope (access/protocol/source/destination/ports) as: $siblings." `
                                -Recommendation "Consolidate duplicate rules into a single rule to reduce redundancy and maintenance overhead." `
                                -ComplianceReference "Internal hygiene / operational efficiency" -RelatedRule $siblings))
                        }
                    }
                }

                #── Priority conflicts / shadowed rules (Custom only) ─────────
                $sortedCustom = @($directionCustomRows | Sort-Object { [int]$_.RulePriority })
                for ($i = 1; $i -lt $sortedCustom.Count; $i++)
                {
                    $current = $sortedCustom[$i]
                    for ($j = 0; $j -lt $i; $j++)
                    {
                        $earlier = $sortedCustom[$j]
                        if ($earlier.RuleAccess -ne $current.RuleAccess -and
                            (Test-ScopeOverlap -ValueA $earlier.RuleProtocol -ValueB $current.RuleProtocol) -and
                            (Test-ScopeOverlap -ValueA $earlier.SourceAddressAll -ValueB $current.SourceAddressAll) -and
                            (Test-ScopeOverlap -ValueA $earlier.DestinationAddressAll -ValueB $current.DestinationAddressAll) -and
                            (Test-PortRangeOverlap -SpecA $earlier.SourcePortAll -SpecB $current.SourcePortAll) -and
                            (Test-PortRangeOverlap -SpecA $earlier.DestinationPortAll -SpecB $current.DestinationPortAll))
                        {
                            $findings.Add((New-Finding -MetaRow $metaRow -RuleName $current.RuleName -RuleDirection $direction -RulePriority $current.RulePriority `
                                -CheckCategory "PriorityConflict" -Severity "Medium" `
                                -FindingText "Rule '$($current.RuleName)' (priority $($current.RulePriority), $($current.RuleAccess)) has an overlapping scope with higher-precedence rule '$($earlier.RuleName)' (priority $($earlier.RulePriority), $($earlier.RuleAccess)); it may be shadowed and never take effect." `
                                -Recommendation "Review rule evaluation order. Either adjust priorities so intent matches evaluation order, or narrow one rule's scope so they no longer overlap." `
                                -ComplianceReference "Internal hygiene / Azure Security Benchmark - NS control family" -RelatedRule $earlier.RuleName))
                            break
                        }
                    }
                }
            }
            #endregion
        }
        catch
        {
            Write-Warning "[ANALYZE] Failed to analyze NSG '$($nsgGroup.Name)': $_. Continuing with remaining NSGs."
            continue
        }
    }
    Write-Host "[ANALYZE] Analysis complete. $($findings.Count) finding(s) identified." -ForegroundColor Green
    Write-Host ""
    #endregion

    #region ── Per-NSG Summary & Compliance Score ────────────────────────────────
    $summaryRows = [System.Collections.Generic.List[PSCustomObject]]::new()
    foreach ($nsgGroup in $nsgGroups)
    {
        $metaRow = $nsgGroup.Group[0]
        $nsgFindings = @($findings | Where-Object { $_.NSGResourceId -eq $metaRow.NSGResourceId })
        $critical = @($nsgFindings | Where-Object { $_.Severity -eq 'Critical' }).Count
        $high     = @($nsgFindings | Where-Object { $_.Severity -eq 'High' }).Count
        $medium   = @($nsgFindings | Where-Object { $_.Severity -eq 'Medium' }).Count
        $low      = @($nsgFindings | Where-Object { $_.Severity -eq 'Low' }).Count
        $info     = @($nsgFindings | Where-Object { $_.Severity -eq 'Informational' }).Count

        $score = 100 - ($critical * 25) - ($high * 10) - ($medium * 5) - ($low * 2)
        if ($score -lt 0) { $score = 0 }

        $summaryRows.Add([PSCustomObject]@{
            SubscriptionName   = $metaRow.SubscriptionName
            ResourceGroup      = $metaRow.ResourceGroup
            NSGName            = $metaRow.NSGName
            NSGResourceId      = $metaRow.NSGResourceId
            CriticalFindings   = $critical
            HighFindings       = $high
            MediumFindings     = $medium
            LowFindings        = $low
            InformationalFindings = $info
            TotalFindings      = $nsgFindings.Count
            ComplianceScore    = $score
            CollectedAtUTC     = $script:CollectedAtUTC
        })
    }
    #endregion

    #region ── Export Reports ────────────────────────────────────────────────────
    if (-not (Test-Path -Path $OutputPath))
    {
        try
        {
            New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
            Write-Host "[EXPORT] Created output directory: $OutputPath" -ForegroundColor Gray
        }
        catch
        {
            Write-Error "[EXPORT] Failed to create output directory '$OutputPath': $_"
            return
        }
    }

    $timestamp = (Get-Date).ToString("yyyyMMdd_HHmmss")
    $findingsFilePath = Join-Path -Path $OutputPath -ChildPath "${ReportPrefix}_Findings_${timestamp}.csv"
    $summaryFilePath  = Join-Path -Path $OutputPath -ChildPath "${ReportPrefix}_Summary_${timestamp}.csv"

    try
    {
        if ($findings.Count -gt 0)
        {
            $findings | Export-Csv -Path $findingsFilePath -NoTypeInformation -Encoding UTF8 -ErrorAction Stop
        }
        else
        {
            [PSCustomObject]@{ Result = "No findings identified." } | Export-Csv -Path $findingsFilePath -NoTypeInformation -Encoding UTF8 -ErrorAction Stop
        }
        $summaryRows | Export-Csv -Path $summaryFilePath -NoTypeInformation -Encoding UTF8 -ErrorAction Stop
    }
    catch
    {
        Write-Error "[EXPORT] Failed to export CSV report(s): $_"
        return
    }

    $jsonFilePath = $null
    if ($IncludeJsonExport)
    {
        $jsonFilePath = Join-Path -Path $OutputPath -ChildPath "${ReportPrefix}_Summary_${timestamp}.json"
        try
        {
            $jsonPayload = [PSCustomObject]@{
                GeneratedAtUTC   = $script:CollectedAtUTC
                SourceCsv        = $CsvPath
                NSGCount         = $nsgGroups.Count
                FindingCounts    = [PSCustomObject]@{
                    Critical      = @($findings | Where-Object { $_.Severity -eq 'Critical' }).Count
                    High          = @($findings | Where-Object { $_.Severity -eq 'High' }).Count
                    Medium        = @($findings | Where-Object { $_.Severity -eq 'Medium' }).Count
                    Low           = @($findings | Where-Object { $_.Severity -eq 'Low' }).Count
                    Informational = @($findings | Where-Object { $_.Severity -eq 'Informational' }).Count
                }
                NSGSummaries     = $summaryRows
            }
            $jsonPayload | ConvertTo-Json -Depth 6 | Out-File -FilePath $jsonFilePath -Encoding UTF8 -ErrorAction Stop
        }
        catch
        {
            Write-Warning "[EXPORT] Failed to export JSON summary: $_"
            $jsonFilePath = $null
        }
    }

    $criticalCount = @($findings | Where-Object { $_.Severity -eq 'Critical' }).Count
    $highCount     = @($findings | Where-Object { $_.Severity -eq 'High' }).Count
    $mediumCount   = @($findings | Where-Object { $_.Severity -eq 'Medium' }).Count
    $lowCount      = @($findings | Where-Object { $_.Severity -eq 'Low' }).Count
    $infoCount     = @($findings | Where-Object { $_.Severity -eq 'Informational' }).Count

    Write-Host ""
    Write-Host "╔══════════════════════════════════════════════════════════════════════╗" -ForegroundColor Green
    Write-Host "║                    OK  COMPLIANCE ANALYSIS COMPLETE                  ║" -ForegroundColor Green
    Write-Host "╠══════════════════════════════════════════════════════════════════════╣" -ForegroundColor Green
    Write-Host "║  NSGs Analyzed         : $($nsgGroups.Count.ToString().PadRight(44))║" -ForegroundColor Green
    Write-Host "║  Critical Findings     : $($criticalCount.ToString().PadRight(44))║" -ForegroundColor $(if ($criticalCount -gt 0) { "Red" } else { "Green" })
    Write-Host "║  High Findings         : $($highCount.ToString().PadRight(44))║" -ForegroundColor $(if ($highCount -gt 0) { "Yellow" } else { "Green" })
    Write-Host "║  Medium Findings       : $($mediumCount.ToString().PadRight(44))║" -ForegroundColor Green
    Write-Host "║  Low Findings          : $($lowCount.ToString().PadRight(44))║" -ForegroundColor Green
    Write-Host "║  Informational         : $($infoCount.ToString().PadRight(44))║" -ForegroundColor Green
    Write-Host "╠══════════════════════════════════════════════════════════════════════╣" -ForegroundColor Green
    Write-Host "║  Reports Saved To:                                                   ║" -ForegroundColor Green
    $truncFindings = if ($findingsFilePath.Length -gt 68) { "..." + $findingsFilePath.Substring($findingsFilePath.Length - 65) } else { $findingsFilePath }
    $truncSummary  = if ($summaryFilePath.Length -gt 68) { "..." + $summaryFilePath.Substring($summaryFilePath.Length - 65) } else { $summaryFilePath }
    Write-Host "║  $($truncFindings.PadRight(68))║" -ForegroundColor Green
    Write-Host "║  $($truncSummary.PadRight(68))║" -ForegroundColor Green
    Write-Host "╚══════════════════════════════════════════════════════════════════════╝" -ForegroundColor Green
    Write-Host ""
    Write-Host "[NEXT STEP] Use these reports as input for:" -ForegroundColor Cyan
    Write-Host "   ► Step 3 : Dashboard & Visualization Script (storytelling & insights)" -ForegroundColor Gray
    Write-Host ""
    #endregion

    if ($FailOnCritical -and $criticalCount -gt 0)
    {
        throw "[FAIL-ON-CRITICAL] $criticalCount Critical-severity finding(s) were identified. See '$findingsFilePath' for details."
    }
}

#region ── Entry Point ────────────────────────────────────────────────────────
if ($MyInvocation.InvocationName -ne ".")
{
    Write-Host ""
    Write-Host "Function 'Test-AzureNSGCompliance' loaded. Usage examples:" -ForegroundColor DarkGray
    Write-Host "   Test-AzureNSGCompliance -CsvPath 'C:\Reports\NSG_Inventory_<timestamp>.csv'" -ForegroundColor White
    Write-Host "   Test-AzureNSGCompliance -CsvPath 'C:\Reports\NSG_Inventory_<timestamp>.csv' -IncludeFlowLogCheck -IncludeJsonExport" -ForegroundColor White
    Write-Host ""
}
#endregion
